apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gtfa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hjls-tenant/rhtap-demo-app/hacbs-test-project-gtfa@sha256:6651e8769d651fee69999b55a89be4922e330163fef6cd7408a19a22ae797bb9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
